openapi: 3.0.1
info:
  title: api
  description: API Definition of api
  version: 1.0.0
servers:
- url: http://localhost:8290/api
paths:
  /:
    get:
      responses:
        default:
          description: Default response
