openapi: 3.0.1
info:
  title: new
  description: API Definition of new
  version: 1.0.0
servers:
- url: http://localhost:8290/new
paths:
  /:
    get:
      responses:
        default:
          description: Default response
